export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const SEARCH_COUNTRY = "SEARCH_COUNTRY";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const ADD_COUNTRY_FAVORITES = "ADD_COUNTRY_FAVORITES";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const DELETE_FROM_FAVORITES = "DELETE_FROM_FAVORITES";